pipeline {
    agent {
         label "maven"
    }
        options {
            skipDefaultCheckout()
            disableConcurrentBuilds()
        }
    stages {
        stage ("preparacion previa de desarrollo"){
            steps{
             script{
                 echo "----------preparacion previa de desarrollo-----------"
                 env.COMPILE_COMMAND = "mvn clean package -DskipTests"
                 env.TEST_COMMAND = "mvn test"
                 env.APP_TEMPLATE = "${env.OPENSHIFT_DIR}/template.yml"
              }
             }
        }

        stage("clonando codigo"){
            steps{
                echo "-------------clonando codigo----------------"
                git([url: "${env.GIT_REPO}", branch: 'master'])
           }
        }

        stage("compilando codigo") {
        steps{
            script{
               echo "----------compilando codigo-----------"

                }
            }
        }
        stage("Test unitarios"){
        steps{
            script{
                echo "-----------------Test unitarios--------------------"

                }
            }
        }
        stage("configurado entorno de desarrollo"){
        steps{
            script{
              echo "-------------------------configurado entorno de desarrollo--------------------------"
            }
        }

        stage("compilando imagen "){
        steps{
           script{
           echo "----------------compilando imagen-----------------------"
                }
             }
        }
        stage("tag imagen"){
        steps{
           script{
           echo "---------------------tag imagen---------------------------"
               openshift.withCluster(){
                  }
                }
            }
        }
        stage("despliegue en desarrollo"){
        steps{
           script{
               echo "---------------------------despliegue en desarrollo-----------------------"
                }
              }
        }

        stage("aplicando configuracion en prod"){
        steps{
            script{
            echo "---------------aplicando configuracion en prod----------------------"
              }
           }
        }
        stage("Copiando imagen del entorno de desarrollo a produccion"){
        steps{
                   script{
                        echo "------------------Copiando imagen del entorno de desarrollo a produccion-----------------------"
                    }
                 }

        }
        stage("deploy image in prod"){
        steps{
           script{
               echo "--------------------------deploy image in prod-----------------------------"
                }
            }
        }
     }
}